function menu() {
  document.getElementById("menu").classList.toggle("show-menu");
  document
    .getElementById("text-1")
    .classList.toggle("show-menu__content__text-div");
  document
    .getElementById("text-2")
    .classList.toggle("show-menu__content__text-div");
  document
    .getElementById("text-3")
    .classList.toggle("show-menu__content__text-div");
  document
    .getElementById("text-4")
    .classList.toggle("show-menu__content__text-div");
  document.getElementById("img-logo").classList.toggle("show-img-logo");
  document
    .getElementById("text-nok")
    .classList.toggle("show-menu__content__text-nok");
  document
    .getElementById("menu__content__text")
    .classList.toggle("show-menu__content__text");
  document
    .getElementById("menu__content")
    .classList.toggle("show-menu__content");
  document
    .getElementById("profile")
    .classList.toggle("show-menu__content__profile");
  document
    .getElementById("profile__text")
    .classList.toggle("show-menu__content__profile__text");
  document
    .getElementById("profile__text2")
    .classList.toggle("show-menu__content__profile__text2");
  document
    .getElementById("arrow1")
    .classList.toggle("show-menu__content__div__arrow");
  document
    .getElementById("arrow2")
    .classList.toggle("show-menu__content__div__arrow");
  document
    .getElementById("arrow3")
    .classList.toggle("show-menu__content__div__arrow");
  document
    .getElementById("arrow4")
    .classList.toggle("show-menu__content__div__arrow");
  document
    .getElementById("puncts")
    .classList.toggle("show-menu__content__puncts");
  document.getElementById("puncts-img").classList.toggle("show-puncts-img");
  document.getElementById("puncts-img2").classList.toggle("show-puncts-img");
  document.getElementById("puncts-img3").classList.toggle("show-puncts-img");
  document.getElementById("puncts-img4").classList.toggle("show-puncts-img");
  document
    .getElementById("personal-page")
    .classList.toggle("show-personal-acc-main-page");
  document
    .getElementById("button-save-min")
    .classList.toggle("show-personal-acc-main-page__content__button-save-min");
  document
    .getElementById("button-save")
    .classList.toggle("show-personal-acc-main-page__content__button-save");
  document
    .getElementById("content2")
    .classList.toggle("show-personal-acc-main-page__content2");
  document
    .getElementById("red")
    .classList.toggle("show-personal-acc-main-page__content__button-red");
  document
    .getElementById("content")
    .classList.toggle("show-personal-acc-main-page__content");
  document
    .getElementById("personal-page")
    .classList.toggle("show-personal-acc-main-page-margin");
  document
    .getElementById("arrow-2")
    .classList.toggle("show-menu__content__cricle-arrow2");
}
function menuMob() {
  document.getElementById("menu-mob").classList.toggle("show-menu-mob");
  document
    .getElementById("menu-mob-menu")
    .classList.toggle("show-menu-mob-menu");
  document.getElementById("crestik").classList.toggle("show-crestik");
}

